"""Add location to batteries

Revision ID: 38ddffe6f04e
Revises: 3ea4ba2f76cf
Create Date: 2026-05-04 22:55:39.195600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ddffe6f04e'
down_revision: Union[str, Sequence[str], None] = '3ea4ba2f76cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batteries', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batteries', type_='foreignkey')
    op.drop_column('batteries', 'location_id')
    # ### end Alembic commands ###
