"""Add price and store tracking

Revision ID: 3a51820bd9d8
Revises: d8fc6660f9a0
Create Date: 2026-05-04 22:49:08.555280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a51820bd9d8'
down_revision: Union[str, Sequence[str], None] = 'd8fc6660f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=True)
    op.add_column('stock_entries', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('stock_entries', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('stock_entries', sa.Column('currency', sa.String(length=10), nullable=False, server_default='RUB'))
    op.create_foreign_key(None, 'stock_entries', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_entries', type_='foreignkey')
    op.drop_column('stock_entries', 'currency')
    op.drop_column('stock_entries', 'store_id')
    op.drop_column('stock_entries', 'price')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
