"""Add unit_id to recipe ingredients

Revision ID: c262593f1c9c
Revises: db452e0cadba
Create Date: 2026-05-04 22:42:05.853372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c262593f1c9c'
down_revision: Union[str, Sequence[str], None] = 'db452e0cadba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe_ingredients', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_column('recipe_ingredients', 'unit_id')
    # ### end Alembic commands ###
