"""Add chores

Revision ID: d8fc6660f9a0
Revises: c262593f1c9c
Create Date: 2026-05-04 22:45:32.337114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fc6660f9a0'
down_revision: Union[str, Sequence[str], None] = 'c262593f1c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_amount', sa.Float(), nullable=True),
    sa.Column('product_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chores_id'), 'chores', ['id'], unique=False)
    op.create_index(op.f('ix_chores_name'), 'chores', ['name'], unique=False)
    op.create_table('chore_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chore_logs_id'), 'chore_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chore_logs_id'), table_name='chore_logs')
    op.drop_table('chore_logs')
    op.drop_index(op.f('ix_chores_name'), table_name='chores')
    op.drop_index(op.f('ix_chores_id'), table_name='chores')
    op.drop_table('chores')
    # ### end Alembic commands ###
