"""Add unit conversions

Revision ID: db452e0cadba
Revises: 6fbf194ae3f8
Create Date: 2026-05-04 22:39:33.604778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db452e0cadba'
down_revision: Union[str, Sequence[str], None] = '6fbf194ae3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_unit_id', sa.Integer(), nullable=False),
    sa.Column('to_unit_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_conversions_id'), 'unit_conversions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_conversions_id'), table_name='unit_conversions')
    op.drop_table('unit_conversions')
    # ### end Alembic commands ###
